export const FETCH_LOADING = 'FETCH_LOADING';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_NEWS_STORIES_SUCCESS = 'FETCH_NEWS_STORIES_SUCCESS';
export const FETCH_MORE_NEWS_STORIES_SUCCESS =
  'FETCH_MORE_NEWS_STORIES_SUCCESS';
export const FETCH_SINGLE_ITEM_SUCCESS = 'FETCH_SINGLE_ITEM_SUCCESS';
